// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package database

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetEventByEventCode(ctx context.Context, eventCode int32) (Event, error)
	GetEventById(ctx context.Context, id uuid.UUID) (Event, error)
	GetMyEvents(ctx context.Context, arg GetMyEventsParams) ([]Event, error)
	GetMyEventsCount(ctx context.Context, userID uuid.UUID) (int64, error)
	GetUpComingEventsCount(ctx context.Context, userID uuid.UUID) (int64, error)
	GetUpcomingEvents(ctx context.Context, arg GetUpcomingEventsParams) ([]Event, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserById(ctx context.Context, id uuid.UUID) (User, error)
}

var _ Querier = (*Queries)(nil)
