version: '3'
services:
  app:
    container_name: crowd-qa-api
    build:
      context: .
      dockerfile: Dockerfile

    ports: 
      - 4040:4040 
    restart: on-failure
    volumes:
      - ./:/app
    env_file: .env
    
    networks:
      - crowd-qa-api
    
  

volumes:
  api:            
             

networks:
  crowd-qa-api:
    driver: bridge